name = "fixreel"
compatibility_date = "2022-09-11"
account_id = "CLOUDFLARE_ACCOUNT_ID"
main = "./dist/worker.js"
send_metrics = false

[build]
command = "npm run build"

[miniflare.globals]
TEST = "true" # Will have unicode character errors in headers if not set to true